services:
  postgres:
    image: 'postgres:latest'
    container_name: financial-postgres
    restart: always
    environment:
      - 'POSTGRES_DB=financial_db'
      - 'POSTGRES_PASSWORD=geraldodetona'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
